name: Node Continuous Intergration
on: push
jobs:
  build:
    name: Build and run node project
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - run: node --version
        name: check node version
      - run: npm --version
        name: check npm version
      - uses: actions/checkout@v4
        name: checkout label version
      - run: npm install
      - run: npm start
