name: Build Weather app with Vite
on: push
jobs:
  build-app:
    name: Build weather app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install npm dependencies
        run: npm install
      - name: Build weather app
        run: npm run build
      - name: Upload static site content
        uses: actions/upload-artifact@v4
        with:
          name: weather-app
          path: dist
